### ISSUE TITLE
TTcolorInts_RA_lvl4_v2 function is missing

### ISSUE THREAD

**Issue by mamun41** [cerdem12/MOBILE#1]
Dear Author,

Thanks for your great work.
In MOBILE_summarize.m, could you check: load('The rest of files')??
When I play with this script, the "TTcolorInts_RA_lvl4_v2" function was found missing.  Could you fix it??

I look forward to hearing from you.

Thanks,
Mamun

**Comment by cerdem12** [comment]
Thanks for reporting the issue. Added the missing function files (https://github.com/cerdem12/MOBILE/commit/8ca5a31e2c3940eea7f4e7c9dcade03a88af6db3). 
The "load('The rest of files')" was meant to be a comment, so fixed that too.
